import { Dimensions, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#fff",
  },
  leftSection: {
    flex: 1,
    alignItems: "flex-start",
  },
  centerSection: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
  },
  rightSection: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 10,
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
  },
  productDetailContainer: {
    backgroundColor: "#fff",
  },
  imageSliderContainer: {
    position: "relative",
  },
  productImage: {
    width: "100%",
    height: 350,
    backgroundColor: "#f8f8f8",
  },
  paginationContainer: {
    position: "absolute",
    bottom: 16,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
  },
  paginationDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "rgba(255, 255, 255, 0.5)",
  },
  paginationDotActive: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#fff",
  },
  imageModalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.9)",
    justifyContent: "center",
    alignItems: "center",
  },
  imageModalCloseButton: {
    position: "absolute",
    top: 50,
    right: 20,
    zIndex: 10,
    padding: 8,
  },
  imageModalSlide: {
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height,
    justifyContent: "center",
    alignItems: "center",
  },
  imageModalImage: {
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height,
  },
  imageModalCounter: {
    position: "absolute",
    bottom: 40,
    alignSelf: "center",
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  imageModalCounterText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  productDetailInfoContainer: {
    padding: 20,
    backgroundColor: "#fff",
  },
  storeNameContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    marginBottom: 12,
  },
  storeName: {
    fontSize: 14,
    color: "#666",
    marginBottom: 8,
  },
  subInfoContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  categoryText: {
    fontSize: 14,
    color: "#666",
  },
  tagRow: {
    flexDirection: "row",
    gap: 6,
    marginTop: 4,
  },
  negoTag: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#FFD700",
    backgroundColor: "#fff",
  },
  negoTagText: {
    fontSize: 12,
    color: "#FFD700",
    fontWeight: "500",
  },
  discountTag: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#4285F4",
    backgroundColor: "#fff",
  },
  discountTagText: {
    fontSize: 12,
    color: "#4285F4",
    fontWeight: "500",
  },
  adultTag: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "rgb(239, 120, 16)",
    backgroundColor: "#fff",
    width: 35,
    height: 22,
    justifyContent: "center",
    alignItems: "center",
  },
  adultTagText: {
    fontSize: 12,
    color: "rgb(239, 120, 16)",
    fontWeight: "500",
  },
  serviceTag: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#009141",
    backgroundColor: "white",
    width: 50,
    height: 22,
    justifyContent: "center",
    alignItems: "center",
  },
  serviceTagText: {
    fontSize: 12,
    color: "#009141",
    fontWeight: "500",
  },
  nameContainer: {
    marginBottom: 10,
    gap: 3,
  },
  productName: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
  },
  iconButton: {
    padding: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  reportButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#555",
    justifyContent: "center",
    alignItems: "center",
  },
  priceAndStockContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  priceContainer: {
    flex: 1,
  },
  originalPrice: {
    fontSize: 14,
    color: "#999",
    textDecorationLine: "line-through",
  },
  discountPriceContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  discountPrice: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
  },
  discountRate: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#EF7810",
  },
  stockContainer: {
    justifyContent: "center",
  },
  stockText: {
    fontSize: 14,
    color: "#777",
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  ratingText: {
    fontSize: 14,
    color: "#777",
    marginLeft: 4,
  },
  tabsContainer: {
    borderTopWidth: 8,
    borderTopColor: "#f5f5f5",
    backgroundColor: "#fff",
  },
  tabs: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
  },
  tab: {
    flex: 1,
    paddingVertical: 16,
    alignItems: "center",
    borderBottomWidth: 3,
    borderBottomColor: "transparent",
    backgroundColor: "#fff",
  },
  activeTab: {
    borderBottomColor: "#EF7810",
  },
  tabText: {
    fontSize: 15,
    fontWeight: "500",
    color: "#999",
  },
  activeTabText: {
    color: "#EF7810",
    fontWeight: "700",
  },
  tabContentContainer: {
    backgroundColor: "#fff",
    minHeight: 400,
  },
  tabContent: {
    fontSize: 14,
    color: "#333",
    lineHeight: 24,
  },
  descriptionContent: {
    width: "100%",
  },
  detailsContent: {
    width: "100%",
    paddingHorizontal: 16,
  },
  reviewsContent: {},
  reviewItem: {
    width: "100%",
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
    backgroundColor: "#fff",
  },
  reviewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  reviewUserName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
  },
  reviewRating: {
    flexDirection: "row",
    gap: 2,
  },
  reviewDate: {
    fontSize: 12,
    color: "#999",
    marginBottom: 8,
  },
  reviewContent: {
    fontSize: 14,
    color: "#555",
    lineHeight: 20,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
    backgroundColor: "#fff",
  },
  detailLabel: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
    color: "#666",
  },
  detailValue: {
    flex: 1,
    fontSize: 14,
    color: "#333",
  },
  detailDropdownContent: {
    paddingHorizontal: 4,
    paddingVertical: 12,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  detailDropdownText: {
    fontSize: 13,
    color: "#555",
    lineHeight: 20,
  },
  actionButtonsContainer: {
    flexDirection: "row",
    padding: 16,
    gap: 12,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
  cartButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#fff",
    borderWidth: 2,
    borderColor: "#EF7810",
    justifyContent: "center",
    alignItems: "center",
  },
  purchaseButton: {
    flex: 1,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#EF7810",
    justifyContent: "center",
    alignItems: "center",
  },
  purchaseButtonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#fff",
  },
  reviewAnswerContainer: {
    marginTop: 8,
    padding: 12,
    backgroundColor: "#fff",
    borderRadius: 8,
  },
  reviewDivider: {
    height: 1,
    backgroundColor: "#f0f0f0",
    marginVertical: 12,
  },
  reviewAnswerLabel: {
    fontSize: 12,
    color: "#666",
  },
  reviewAnswerText: {
    fontSize: 14,
    color: "#333",
    marginTop: 4,
  },
  noReviewsContainer: {
    padding: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  noReviewsText: {
    marginTop: 12,
    fontSize: 14,
    color: "#999",
  },
  scrollToTopButton: {
    position: "absolute",
    right: 20,
    bottom: 30,
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: "#EF7810",
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    boxShadow: "0 0 5px rgba(0,0,0,0.2)",
  },
});
