import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 20,
    backgroundColor: "#fff",
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "flex-start",
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    position: "absolute",
    left: 0,
    right: 0,
    textAlign: "center",
    pointerEvents: "none",
  },
  placeholder: {
    width: 40,
  },
  addButton: {
    width: 44,
    height: 44,
    borderWidth: 1,
    borderColor: "#EF7810",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
  },
  addProductButton: {
    borderWidth: 1,
    borderColor: "#EF7810",
    marginHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  content: {
    flex: 1,
    backgroundColor: "#fff",
    justifyContent: "center",
    paddingVertical: 10,
    marginVertical: 5,
    borderRadius: 10,
    boxShadow: "0 0px 6px rgba(0,0,0,0.1)",
  },
  productTouchable: {
    justifyContent: "flex-start",
  },
  productContainer: {
    flexDirection: "row",
    borderRadius: 10,
    overflow: "hidden",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingVertical: 20,
    paddingHorizontal: 10,
  },
  productImageContainer: {
    width: 130,
    height: 130,
  },
  productImage: {
    width: "100%",
    height: "100%",
  },
  productInfoContainer: {
    flex: 1,
    paddingHorizontal: 15,
    justifyContent: "center",
  },
  categoryName: {
    fontSize: 12,
    color: "#888",
  },
  productName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#000",
    marginBottom: 4,
  },
  price: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#EF7810",
  },
  productButtonContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    marginVertical: 10,
    marginHorizontal: 20,
  },
  saleButton: {
    flex: 1,
    backgroundColor: "#fff",
    borderColor: "#EF7810",
    borderWidth: 1,
    paddingVertical: 6,
    borderRadius: 6,
    marginRight: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  saleButtonText: {
    color: "#EF7810",
    fontSize: 14,
    fontWeight: "bold",
  },
  negoButton: {
    flex: 1,
    backgroundColor: "#fff",
    borderColor: "#EF7810",
    borderWidth: 1,
    paddingVertical: 6,
    borderRadius: 6,
    marginLeft: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  negoButtonText: {
    color: "#EF7810",
    fontSize: 14,
    fontWeight: "bold",
  },
  moreButton: {
    backgroundColor: "#fff",
    borderColor: "#ddd",
    borderWidth: 1,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 6,
    marginLeft: 8,
    justifyContent: "center",
    alignItems: "center",
  },

  // 모달 스타일
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 12,
    minWidth: 160,
    overflow: "hidden",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  modalButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 20,
    gap: 12,
  },
  modalButtonText: {
    fontSize: 16,
    color: "#333",
    fontWeight: "500",
  },
  modalDivider: {
    height: 1,
    backgroundColor: "#F0F0F0",
  },

  deleteModalContent: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 24,
    width: "90%",
    maxWidth: 380,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  deleteModalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 12,
    textAlign: "center",
  },
  deleteModalMessage: {
    fontSize: 14,
    color: "#666",
    lineHeight: 22,
    textAlign: "center",
    marginBottom: 24,
  },
  deleteModalButtons: {
    flexDirection: "row",
    gap: 12,
  },
  deleteModalButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  cancelButton: {
    backgroundColor: "#F5F5F5",
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#666",
  },
  confirmButton: {
    backgroundColor: "#FF3B30",
  },
  confirmButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
  },
  
  // Sale Modal
  saleModalWrapper: {
    width: '90%',
    alignSelf: 'center',
  },
  saleModalContent: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 20,
    width: '100%',
    maxWidth: 700,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  saleModalHeader: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  saleModalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
  },
  saleOptionGroup: {
    marginBottom: 14,
  },
  saleLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#333",
    marginBottom: 8,
  },
  saleRadioGroup: {
    flexDirection: "row",
    gap: 12,
    flexWrap: "wrap",
  },
  saleRadioOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  saleRadioCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#ef7810",
    justifyContent: "center",
    alignItems: "center",
  },
  saleRadioCircleSelected: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#ef7810",
  },
  saleRadioText: {
    fontSize: 14,
    color: "#333",
  },
  saleInputGroup: {
    marginBottom: 14,
  },
  saleInput: {
    backgroundColor: "#f8f8f8",
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 12,
    fontSize: 14,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    color: "#333",
  },
  saleInputDisabled: {
    backgroundColor: "#f0f0f0",
    borderColor: "#d0d0d0",
  },
  saleInputDisabledText: {
    fontSize: 14,
    color: "#999",
  },
  saleDateButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#fff5ed",
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: "#ef7810",
  },
  saleDateText: {
    fontSize: 14,
    color: "#ef7810",
    fontWeight: "500",
  },
  saleHelpText: {
    fontSize: 12,
    color: "#999",
    marginTop: 6,
    lineHeight: 18,
  },
  saleModalButtons: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  saleCancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: "#f5f5f5",
    alignItems: "center",
  },
  saleCancelButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#666",
  },
  saleConfirmButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: "#ef7810",
    alignItems: "center",
  },
  saleConfirmButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
  },
  
  // Nego Modal
  negoModalContent: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 24,
    width: "90%",
    maxWidth: 380,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
});
