import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  saleModalWrapper: {
    width: "90%",
    alignSelf: "center",
  },
  saleModalContent: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 20,
    width: "100%",
    maxWidth: 700,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  saleModalHeader: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  saleModalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1F2937",
  },
  saleLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#374151",
    marginBottom: 8,
  },
  saleInputGroup: {
    marginBottom: 14,
  },
  saleInput: {
    backgroundColor: "#F9FAFB",
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 12,
    fontSize: 14,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    color: "#1F2937",
  },
  saleInputDisabled: {
    backgroundColor: "#F3F4F6",
    borderColor: "#D1D5DB",
  },
  saleInputDisabledText: {
    fontSize: 14,
    color: "#6B7280",
  },
  saleDateButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#fff5ed",
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: "#ef7810",
  },
  saleDateTimeRow: {
    flexDirection: "row",
    gap: 8,
  },
  saleDateButtonHalf: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#fff5ed",
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: "#ef7810",
  },
  salePickerWrapper: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff5ed",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ef7810",
    paddingLeft: 12,
    paddingVertical: 4,
    minHeight: 48,
    overflow: "hidden",
  },
  salePickerIcon: {
    marginRight: 4,
  },
  salePicker: {
    flex: 1,
    height: 50,
    color: "#ef7810",
  },
  saleDateText: {
    fontSize: 14,
    color: "#ef7810",
    fontWeight: "500",
  },
  saleHelpText: {
    fontSize: 12,
    color: "#9CA3AF",
    marginTop: 6,
    lineHeight: 18,
  },
  saleModalButtons: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  saleCancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: "#F3F4F6",
    alignItems: "center",
  },
  saleCancelButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#4B5563",
  },
  saleConfirmButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: "#ef7810",
    alignItems: "center",
  },
  saleConfirmButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
  },
});
