import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#fff",
  },
  leftSection: {
    flex: 1,
    alignItems: "flex-start",
  },
  centerSection: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
  },
  rightSection: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
  },
  locationButton: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "flex-end",
  },
  mapContainer: {
    flex: 1,
    overflow: "visible",
  },
  webView: {
    flex: 1,
  },
  textInput: {
    height: 30,
    fontSize: 16,
    textAlign: "left",
    color: "#000",
    paddingVertical: 0,
    textAlignVertical: "center",
    justifyContent: "center",
  },
  searchContainer: {
    position: "absolute",
    top: 12,
    left: 20,
    right: 20,
    paddingVertical: 12,
    backgroundColor: "#fff",
    borderRadius: 10,
    paddingHorizontal: 15,
    zIndex: 10,
  },
  storeInfoContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingTop: 30,
    minHeight: 220,
  },
  closeButton: {
    position: "absolute",
    top: 15,
    right: 15,
    zIndex: 1,
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
  },
  storeName: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 8,
  },
  storeAddress: {
    fontSize: 14,
    color: "#666",
    marginBottom: 8,
  },
  storePhone: {
    fontSize: 13,
    color: "#4285F4",
    marginBottom: 12,
  },
  loadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 100,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 18,
    color: "#fff",
    fontWeight: "500",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
  },
  modalCloseButton: {
    padding: 4,
  },
  searchTextPlaceholder: {
    fontSize: 16,
    color: "#999",
  },
  searchTextActive: {
    fontSize: 16,
    color: "#000",
  },
  statusBar: {
    backgroundColor: "#fff",
  },
  modalContent: {
    flex: 1,
    paddingTop: 0,
  },
  modalEmptyView: {
    width: 28,
  },
  postcodeStyle: {
    flex: 1,
  },
  storeDetailContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 16,
    paddingTop: 48,
    paddingBottom: 20,
    zIndex: 30,
  },
  storeDetailContent: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  storeDetailInfo: {
    flex: 1,
    gap: 4,
  },
  storeDetailImageWrapper: {
    width: 80,
    height: 80,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "#f5f5f5",
    flexShrink: 0,
  },
  storeDetailImage: {
    width: "100%",
    height: "100%",
  },
  storeDetailImagePlaceholder: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
  },
  clickedLocationContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 16,
    zIndex: 20,
  },
  clickedLocationContent: {
    gap: 12,
    marginBottom: 16,
  },
  clickedLocationHeader: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  clickedLocationCloseButton: {
    padding: 8,
    marginRight: -8,
  },
  clickedLocationAddress: {
    fontSize: 18,
    color: "#555",
    fontWeight: "500",
    lineHeight: 20,
  },
  searchButton: {
    flexDirection: "row",
    backgroundColor: "#EF7810",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 8,
  },
  searchButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  cancelButtonText: {
    color: "#666",
    fontSize: 12,
    fontWeight: "500",
  },
  storeListContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "40%",
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    zIndex: 10,
  },
  storeListHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  storeListTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#333",
  },
  storeListCloseButton: {
    padding: 8,
    marginRight: -8,
  },
  storeListItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  storeListItemName: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
    marginBottom: 4,
  },
  storeListItemAddress: {
    fontSize: 16,
    color: "#666",
    marginBottom: 4,
  },
  storeListItemPhone: {
    fontSize: 15,
    color: "#999",
    fontWeight: "500",
  },
});
