import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#fff",
  },
  leftSection: {
    flex: 1,
    alignItems: "flex-start",
  },
  centerSection: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
  },
  rightSection: {
    flex: 1,
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
  },
  listContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingBottom: 80,
  },
  itemContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    marginBottom: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#EEEEEE",
  },
  itemHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#EEEEEE",
  },
  itemDateTime: {
    marginTop: 4,
    fontSize: 13,
    fontWeight: "500",
    color: "#999999",
  },
  itemContent: {
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: "#FFFFFF",
  },
  itemImageContainer: {
    width: 80,
    height: 80,
    borderWidth: 1,
    borderColor: "#EEEEEE",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FAFAFA",
    overflow: "hidden",
  },
  itemImage: {
    width: "100%",
    height: "100%",
  },
  itemDetails: {
    flex: 1,
    justifyContent: "space-between",
  },
  storeName: {
    fontSize: 13,
    fontWeight: "500",
    color: "#999999",
    marginBottom: 4,
  },
  productName: {
    fontSize: 15,
    fontWeight: "600",
    color: "#333333",
    marginBottom: 8,
    lineHeight: 20,
  },
  requestPrice: {
    fontSize: 15,
    fontWeight: "700",
    color: "#EF7810",
  },
  originalPrice: {
    fontSize: 12,
    fontWeight: "500",
    color: "#999999",
    textDecorationLine: "line-through",
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 5,
    overflow: "hidden",
    backgroundColor: "#E8F5E9",
  },
  statusText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#4CAF50",
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 80,
  },
  emptyText: {
    fontSize: 15,
    color: "#999999",
    marginTop: 16,
    fontWeight: "500",
  },
  itemFooter: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: "#fff",
  },
  paymentButton: {
    flex: 1,
    paddingVertical: 12,
    backgroundColor: "#EF7810",
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  paymentButtonText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  viewDetailButton: {
    flex: 1,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "#EF7810",
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  viewDetailButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#EF7810",
  },
});
