import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#ffffff",
    },
    headerContainer: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        padding: 20,
        backgroundColor: "#fff",
    },
    backButton: {
        width: 44,
        height: 44,
        justifyContent: "center",
        alignItems: "flex-start",
    },
    title: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#333",
        position: "absolute",
        left: 0,
        right: 0,
        textAlign: "center",
        pointerEvents: "none",
    },
    placeholder: {
        width: 40,
    },
    tabContainer: {
        flexDirection: "row",
        justifyContent: "space-around",
        backgroundColor: "#ffffff",
        borderBottomWidth: 1,
        borderBottomColor: "#eee",
    },
    tabButton: {
        paddingVertical: 16,
        width: "50%",
        alignItems: "center",
        justifyContent: "center",
    },
    tabButtonActive: {
        borderBottomWidth: 1,
        borderBottomColor: "#EF7810",
    },
    tabButtonText: {
        fontSize: 16,
        color: "#555",
        fontWeight: "bold",
    },
    tabButtonTextActive: {
        color: "#EF7810",
    },
    inactiveTabBorder: {
        borderBottomWidth: 1,
        borderBottomColor: "#ccc",
    },
    listContainer: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        paddingBottom: 80,
    },
    itemContainer: {
        backgroundColor: "#FFFFFF",
        borderRadius: 10,
        marginBottom: 12,
        overflow: "hidden",
        borderWidth: 1,
        borderColor: "#EEEEEE",
    },
    itemHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: "#fff",
        borderBottomWidth: 1,
        borderBottomColor: "#EEEEEE",
    },
    itemDateTime: {
        marginTop: 4,
        fontSize: 13,
        fontWeight: "500",
        color: "#999999",
    },
    itemContent: {
        flexDirection: "row",
        gap: 12,
        paddingHorizontal: 16,
        paddingVertical: 14,
        backgroundColor: "#FFFFFF",
    },
    itemImageContainer: {
        width: 80,
        height: 80,
        borderWidth: 1,
        borderColor: "#EEEEEE",
        borderRadius: 8,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#FAFAFA",
        overflow: "hidden",
    },
    itemImage: {
        width: "100%",
        height: "100%",
    },
    itemDetails: {
        flex: 1,
        justifyContent: "space-between",
    },
    storeName: {
        fontSize: 13,
        fontWeight: "500",
        color: "#999999",
        marginBottom: 4,
    },
    productName: {
        fontSize: 15,
        fontWeight: "600",
        color: "#333333",
        marginBottom: 8,
        lineHeight: 20,
    },
    priceRow: {
        gap: 8,
    },
    requestPrice: {
        fontSize: 15,
        fontWeight: "700",
        color: "#EF7810",
    },
    originalPrice: {
        fontSize: 12,
        fontWeight: "500",
        color: "#999999",
        textDecorationLine: "line-through",
    },
    statusBadge: {
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 5,
        overflow: "hidden",
    },
    statusBadgeApproved: {
        backgroundColor: "#E8F5E9",
    },
    statusBadgeRejected: {
        backgroundColor: "#FFEBEE",
    },
    statusBadgeCanceled: {
        backgroundColor: "#FFF3E0",
    },
    statusText: {
        fontSize: 12,
        fontWeight: "600",
    },
    statusTextApproved: {
        color: "#4CAF50",
    },
    statusTextRejected: {
        color: "#F44336",
    },
    statusTextCanceled: {
        color: "#FF9800",
    },
    emptyContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        paddingVertical: 80,
    },
    emptyText: {
        fontSize: 15,
        color: "#999999",
        marginTop: 16,
        fontWeight: "500",
    },
    itemFooter: {
        flexDirection: "row",
        gap: 10,
        paddingHorizontal: 16,
        paddingBottom: 12,
        backgroundColor: "#fff",
    },
    editButton: {
        flex: 1,
        paddingVertical: 10,
        borderWidth: 1,
        borderColor: "#EF7810",
        borderRadius: 6,
        alignItems: "center",
        justifyContent: "center",
    },
    editButtonText: {
        fontSize: 13,
        fontWeight: "600",
        color: "#EF7810",
    },
    cancelButton: {
        flex: 1,
        paddingVertical: 10,
        borderWidth: 1,
        borderColor: "#CCCCCC",
        borderRadius: 6,
        alignItems: "center",
        justifyContent: "center",
    },
    cancelButtonText: {
        fontSize: 13,
        fontWeight: "600",
        color: "#666666",
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        justifyContent: "center",
        alignItems: "center",
    },
    negoModalContent: {
        backgroundColor: "#fff",
        borderRadius: 16,
        padding: 24,
        width: "85%",
        maxWidth: 340,
        elevation: 5,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
    },
    negoModalTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#333333",
        marginBottom: 12,
        textAlign: "center",
    },
    negoModalLabel: {
        fontSize: 14,
        fontWeight: "600",
        color: "#374151",
        marginBottom: 4,
        marginTop: 16,
    },
    negoModalSubLabel: {
        fontSize: 12,
        color: "#666666",
        marginBottom: 12,
        lineHeight: 18,
    },
    negoInput: {
        borderWidth: 1,
        borderColor: "#D1D5DB",
        borderRadius: 8,
        padding: 12,
        fontSize: 16,
        color: "#1F2937",
        backgroundColor: "#fff",
    },
    negoAmountDisplay: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#EF7810",
        marginTop: 12,
        marginBottom: 20,
        textAlign: "right",
    },
    negoModalButtons: {
        flexDirection: "row",
        gap: 12,
        marginTop: 24,
    },
    negoModalButton: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 8,
        alignItems: "center",
    },
    negoConfirmButton: {
        backgroundColor: "#EF7810",
    },
    negoConfirmButtonText: {
        fontSize: 16,
        fontWeight: "600",
        color: "#fff",
    },
    negoCancelButton: {
        backgroundColor: "#F3F4F6",
    },
    negoCancelButtonText: {
        fontSize: 16,
        fontWeight: "600",
        color: "#4B5563",
    },
});
