import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#fff",
  },
  leftSection: {
    flex: 1,
    alignItems: "flex-start",
  },
  centerSection: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
  },
  rightSection: {
    flex: 1,
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
  },
  searchTopContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#FFFFFF",
  },
  searchText: {
    flex: 1,
    fontSize: 14,
    color: "#333333",
    paddingHorizontal: 12,
    paddingVertical: 15,
    borderWidth: 1,
    borderColor: "#EEEEEE",
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
  },
  searchTextFocused: {
    borderColor: "#EF7810",
    backgroundColor: "#FFF5F0",
  },
  searchButton: {
    paddingHorizontal: 18,
    paddingVertical: 15,
    borderWidth: 1.5,
    borderRadius: 8,
    borderColor: "rgb(239, 120, 16)",
    backgroundColor: "rgb(239, 120, 16)",
  },
  searchButtonText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#fff",
  },
  filterContainer: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 10,
    backgroundColor: "#FFFFFF",
  },
  selectBox: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#EEEEEE",
    borderRadius: 8,
    backgroundColor: "#fff",
    gap: 6,
  },
  selectBoxText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#666666",
  },
  listContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingBottom: 120,
  },
  orderContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    marginBottom: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#EEEEEE",
  },
  orderDateContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#FAFAFA",
  },
  orderDate: {
    fontSize: 15,
    fontWeight: "700",
    color: "#333333",
  },
  orderItemContainer: {
    borderTopWidth: 1,
    borderTopColor: "#EEEEEE",
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  topInfoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  orderState: {
    backgroundColor: "rgb(239, 120, 16)",
    fontSize: 14,
    fontWeight: "600",
    color: "#fff",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 5,
    overflow: "hidden",
  },
  orderDetailButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "#EEEEEE",
    borderRadius: 6,
    backgroundColor: "#FFFFFF",
  },
  orderDetailButtonText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#666666",
  },
  orderProductInfoContainer: {
    flexDirection: "row",
    gap: 12,
    alignItems: "flex-start",
  },
  orderProductImgContainer: {
    width: 80,
    height: 80,
    borderWidth: 1,
    borderColor: "#EEEEEE",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FAFAFA",
    overflow: "hidden",
  },
  orderProductImg: {
    width: "100%",
    height: "100%",
  },
  orderProductDetailContainer: {
    flex: 1,
    justifyContent: "space-between",
  },
  productName: {
    fontSize: 15,
    fontWeight: "600",
    color: "#333333",
    marginBottom: 8,
    lineHeight: 20,
  },
  bottomInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  productPrice: {
    fontSize: 15,
    fontWeight: "700",
    color: "#EF7810",
  },
  modalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    zIndex: 999,
  },
  modalContentWrapper: {
    flex: 1,
    justifyContent: "flex-end",
  },
  filterModalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 16,
    paddingBottom: 30,
    maxHeight: "80%",
  },
  filterSection: {
    marginBottom: 24,
  },
  filterSectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#333333",
    marginBottom: 12,
  },
  filterOptionButtonText: {
    fontSize: 15,
    fontWeight: "500",
    color: "#333333",
  },
  filterOptions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  filterOptionButton: {
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: "#EEEEEE",
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
  },
  filterOptionButtonActive: {
    borderColor: "#EF7810",
    backgroundColor: "#FFF5F0",
  },
  filterDateOptions: {
    gap: 8,
  },
  filterDateButton: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#EEEEEE",
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
  },
  filterDateButtonActive: {
    borderColor: "#EF7810",
    backgroundColor: "#FFF5F0",
  },
  applyButton: {
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: "#EF7810",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 24,
    shadowColor: "#EF7810",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  applyButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },
  scrollToTopButton: {
    position: "absolute",
    right: 20,
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: "#EF7810",
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 4,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 80,
  },
  emptyText: {
    fontSize: 15,
    color: "#999999",
    marginTop: 16,
    marginBottom: 24,
    fontWeight: "500",
  },
  refreshButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1.5,
    borderColor: "#EF7810",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    gap: 8,
  },
  refreshButtonText: {
    color: "#EF7810",
    fontSize: 14,
    fontWeight: "600",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    padding: 16,
    minWidth: 200,
  },
  modalItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    fontSize: 16,
  },
  orderTopContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 3,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#EEEEEE",
  },
  filterModalCloseButton: {
    fontSize: 20,
    color: "#666666",
  },
});
