import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#fff",
  },
  leftSection: {
    flex: 1,
    alignItems: "flex-start",
  },
  centerSection: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
  },
  rightSection: {
    flex: 1,
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
  },
  filterContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
    gap: 8,
  },
  filterButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#ddd",
    backgroundColor: "#fff",
  },
  filterButtonActive: {
    backgroundColor: "#EF7810",
    borderColor: "#EF7810",
  },
  filterButtonText: {
    fontSize: 14,
    color: "#666",
    fontWeight: "500",
  },
  filterButtonTextActive: {
    color: "#fff",
    fontWeight: "600",
  },
  resetButton: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: "auto",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#ddd",
    backgroundColor: "#f8f8f8",
    gap: 4,
  },
  resetButtonText: {
    fontSize: 14,
    color: "#666",
    fontWeight: "500",
  },
  listContent: {
    paddingVertical: 20,
  },
  columnWrapper: {
    justifyContent: "space-between",
    paddingHorizontal: 10,
  },
  listItemWrapper: {
    flex: 1,
    maxWidth: "48%",
    marginBottom: 20,
  },
  productItemContainer: {
    flexDirection: "column",
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 8,
    overflow: "hidden",
    elevation: 2,
    paddingBottom: 16,
  },
  productImage: {
    width: "100%",
    height: 200,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#eee",
    marginBottom: 8,
  },
  productInfo: {
    marginLeft: 12,
    marginRight: 12,
    flex: 1,
    justifyContent: "center",
    alignSelf: "flex-start",
    width: "100%",
  },
  productName: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 10,
    width: "100%",
  },
  storeName: {
    fontSize: 14,
    color: "#666",
    width: "100%",
  },
  priceContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  discountText: {
    fontSize: 18,
    color: "#EF7810",
    marginLeft: 10,
    fontWeight: "bold",
  },
  priceText: {
    fontSize: 18,
    color: "#333",
    fontWeight: "bold",
  },
  originalPriceText: {
    fontSize: 18,
    color: "#999",
    textDecorationLine: "line-through",
  },
  reviewText: {
    fontSize: 16,
    color: "#888",
  },
});
