import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#fff",
  },
  leftSection: {
    flex: 1,
    alignItems: "flex-start",
  },
  centerSection: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
  },
  rightSection: {
    flex: 1,
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
  },
  questionItemContainer: {
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  questionItemTitleText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#000",
    marginBottom: 8,
  },
  questionTypeSelector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#CCC",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#ffffffff",
  },
  questionTypeSelectorText: {
    fontSize: 14,
    color: "#666",
  },
  questionTitleInput: {
    color: "#666",
    borderWidth: 1,
    borderColor: "#CCC",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#ffffffff",
  },
  questionContentInput: {
    color: "#666",
    borderWidth: 1,
    borderColor: "#CCC",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#ffffffff",
    height: 120,
    textAlignVertical: "top",
  },
  questionItemContentText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#000",
    marginBottom: 8,
  },
  fileUploadButton: {
    borderWidth: 1,
    borderColor: "#CCC",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#ffffffff",
    alignItems: "center",
  },
  fileUploadButtonText: {
    fontSize: 14,
    color: "#666",
  },

  questionImageContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  photoSlot: {
    width: 100,
    height: 100,
    borderRadius: 8,
    overflow: "hidden",
  },
  photoWrapper: {
    width: "100%",
    height: "100%",
    position: "relative",
  },
  questionImage: {
    width: "100%",
    height: "100%",
  },
  removePhotoButton: {
    position: "absolute",
    top: 4,
    right: 4,
    backgroundColor: "transparent",
  },
  photoUploadButton: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
    borderWidth: 1,
    borderColor: "#e0e0e0",
    borderRadius: 8,
  },

  submitButtonContainer: {
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  submitButton: {
    flex: 1,
    paddingVertical: 12,
    borderColor: "#EF7810",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderRadius: 6,
    alignItems: "center",
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "#d0d0d0",
    borderRadius: 6,
    alignItems: "center",
  },
  submitButtonText: {
    fontSize: 14,
    color: "#EF7810",
    fontWeight: "600",
  },
  cancelButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#666",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 24,
    paddingVertical: 28,
    width: "85%",
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#000",
    marginBottom: 24,
    textAlign: "center",
  },
  modalOption: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  modalOptionText: {
    fontSize: 14,
    color: "#333",
    textAlign: "center",
  },
});
