import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 12,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  leftSection: {
    flex: 1,
    alignItems: "flex-start",
  },
  centerSection: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
  },
  rightSection: {
    flex: 1,
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
  },
  productInfoContainer: {
    marginHorizontal: 16,
    marginTop: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: "#fff",
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  productInfoRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  productImage: {
    width: 72,
    height: 72,
    borderRadius: 10,
    marginRight: 14,
  },
  productImagePlaceholder: {
    width: 72,
    height: 72,
    borderRadius: 10,
    marginRight: 14,
    backgroundColor: "#f0f0f0",
    justifyContent: "center",
    alignItems: "center",
  },
  productImagePlaceholderText: {
    color: "#bbb",
    fontSize: 12,
  },
  productDetails: {
    flex: 1,
    justifyContent: "center",
  },
  storeName: {
    fontSize: 12,
    color: "#999",
    marginBottom: 4,
  },
  productName: {
    fontSize: 15,
    fontWeight: "600",
    color: "#222",
    lineHeight: 21,
  },
  reviewImagesSection: {
    marginHorizontal: 16,
    marginTop: 12,
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingVertical: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  reviewImagesContentContainer: {
    paddingHorizontal: 16,
  },
  reviewImageItem: {
    width: 110,
    height: 110,
    borderRadius: 10,
    marginRight: 8,
  },
  reviewCard: {
    marginHorizontal: 16,
    marginTop: 12,
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: "#fff",
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  ratingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  ratingText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#EF7810",
    marginLeft: 6,
  },
  regDateText: {
    fontSize: 12,
    color: "#bbb",
  },
  divider: {
    height: 1,
    backgroundColor: "#f0f0f0",
    marginBottom: 14,
  },
  contentText: {
    fontSize: 14,
    color: "#444",
    lineHeight: 22,
  },
  actionButtonsContainer: {
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 20,
    flexDirection: "row",
    gap: 10,
  },
  editButton: {
    flex: 1,
    paddingVertical: 13,
    backgroundColor: "#fff",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#EF7810",
    alignItems: "center",
  },
  editButtonText: {
    color: "#EF7810",
    fontWeight: "600",
    fontSize: 15,
  },
  deleteButton: {
    flex: 1,
    paddingVertical: 13,
    backgroundColor: "#fff",
    borderColor: "#ddd",
    borderWidth: 1,
    borderRadius: 10,
    alignItems: "center",
  },
  deleteButtonText: {
    color: "#555",
    fontWeight: "600",
    fontSize: 15,
  },
  safeAreaBottom: {
    backgroundColor: "#f5f6f8",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 24,
    paddingVertical: 24,
    width: "80%",
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#333",
    marginBottom: 8,
  },
  modalMessage: {
    fontSize: 14,
    color: "#666",
    marginBottom: 24,
  },
  modalButtonsContainer: {
    flexDirection: "row",
    gap: 8,
  },
  modalConfirmButton: {
    flex: 1,
    paddingVertical: 12,
    backgroundColor: "rgb(239, 120, 16)",
    borderRadius: 4,
    alignItems: "center",
  },
  modalConfirmButtonText: {
    color: "#fff",
    fontWeight: "600",
  },
  modalCancelButton: {
    flex: 1,
    paddingVertical: 12,
    backgroundColor: "#f0f0f0",
    borderRadius: 4,
    alignItems: "center",
  },
  modalCancelButtonText: {
    color: "#333",
    fontWeight: "600",
  },
  starIcon: {
    marginRight: 4,
  },
  insetTopView: {
    backgroundColor: "#fff",
  },
  answerSection: {
    marginHorizontal: 16,
    marginTop: 12,
    padding: 16,
    backgroundColor: "#FFF8F3",
    borderRadius: 12,
    borderLeftWidth: 3,
    borderLeftColor: "#EF7810",
    shadowColor: "#EF7810",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  answerLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: "#EF7810",
    marginBottom: 6,
  },
  answerContent: {
    fontSize: 14,
    color: "#333",
    lineHeight: 20,
  },
  answerDate: {
    fontSize: 11,
    color: "#999",
    marginTop: 8,
    textAlign: "right",
  },
});
